#!/bin/bash
ROUTER_ID=128.223.60.102
YEAR=`date "+%Y"`
MONTH=`date "+%m"`

FILENAME=oix-full-snapshot-latest.dat
FILENAME_COMPRESSED="$FILENAME.bz2"


if [ -f "/var/pwhois/$FILENAME" ]; then
	rm -f "/var/pwhois/$FILENAME";
fi

if [ -f "/var/pwhois/$FILENAME_COMPRESSED" ]; then
	rm -f "/var/pwhois/$FILENAME_COMPRESSED";
fi

cd /var/pwhois
/usr/bin/wget -q http://archive.routeviews.org/oix-route-views/$YEAR.$MONTH/$FILENAME_COMPRESSED
ln -f /var/pwhois/$FILENAME_COMPRESSED /var/pwhois/$FILENAME_COMPRESSED.old
bunzip2 -f /var/pwhois/$FILENAME_COMPRESSED
if [ -r "/var/pwhois/$FILENAME" ]; then
	/usr/local/sbin/pwhois-updatedb -i /var/pwhois/$FILENAME -r $ROUTER_ID --no-fib -v -l /var/log/pwhois-updatedb.log
	rm /var/pwhois/$FILENAME
else
	echo "Error: no snapshot downloaded";
	exit -1;
fi
