set character_set_client=latin1;
LOAD DATA LOCAL INFILE '/<BASE>/pwhois/mysql/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE.CSV' REPLACE INTO TABLE ipcitylatlong CHARACTER SET latin1 COLUMNS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 1 LINES;
-- COPY ipcitylatlong FROM '/<BASE>/pwhois/mysql/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE.CSV' WITH CSV;
