ALTER TABLE asn ADD COLUMN adminhandle VARCHAR(30) DEFAULT NULL AFTER updatedate;
ALTER TABLE asn ADD COLUMN mailbox VARCHAR(64) DEFAULT NULL AFTER as_orgname;
ALTER TABLE netblock ADD COLUMN mailbox VARCHAR(64) DEFAULT NULL AFTER orgname;
